$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$sourceRoot = Join-Path $repoRoot 'assets\textures'
$outputPath = Join-Path $repoRoot 'platform\native\texture_atlas.c'
$tileNames = @('stone_generic.png', 'dirt.png', 'grass_side.png', 'grass_top.png')
$tileSize = 16
$atlasWidth = $tileSize * $tileNames.Count
$atlasHeight = $tileSize

Add-Type -AssemblyName System.Drawing
$images = @()
try {
  foreach ($tileName in $tileNames) {
    $path = Join-Path $sourceRoot $tileName
    if (!(Test-Path -LiteralPath $path -PathType Leaf)) {
      throw "Texture source was not found: $path"
    }
    $image = [System.Drawing.Bitmap]::new($path)
    if ($image.Width -ne $tileSize -or $image.Height -ne $tileSize) {
      $image.Dispose()
      throw "Texture must be ${tileSize}x${tileSize}: $path"
    }
    $images += $image
  }

  $bytes = [System.Collections.Generic.List[string]]::new()
  for ($y = $atlasHeight - 1; $y -ge 0; $y--) {
    for ($atlasX = 0; $atlasX -lt $atlasWidth; $atlasX++) {
      $tileIndex = [Math]::Floor($atlasX / $tileSize)
      $localX = $atlasX % $tileSize
      $pixel = $images[$tileIndex].GetPixel($localX, $y)
      $bytes.Add(('0x{0:X2}, 0x{1:X2}, 0x{2:X2}, 0x{3:X2}' -f $pixel.R, $pixel.G, $pixel.B, $pixel.A))
    }
  }

  $content = @"
/* Generated by scripts/generate-texture-atlas.ps1. Do not edit by hand. */
const unsigned char lunarrender_texture_atlas_rgba[] = {
  $($bytes -join ",`n  ")
};
const int lunarrender_texture_atlas_width = $atlasWidth;
const int lunarrender_texture_atlas_height = $atlasHeight;
"@
  [System.IO.File]::WriteAllText($outputPath, $content, [System.Text.UTF8Encoding]::new($false))
  Write-Output "Generated $outputPath ($atlasWidth x $atlasHeight RGBA)."
}
finally {
  foreach ($image in $images) {
    $image.Dispose()
  }
}
